### ISSUE TITLE
Compatibility for Cypress 10 files change to cy.ts and cy.js

### ISSUE THREAD

**Issue by jdini76** [dzhavat/test-focus-highlighter#11]
in Cypress 10. the Spec files are changed to be .cy.ts and .cy.js as apposed to .spec.ts and .spec.js.  This breaks the highlighter functionality.

**Comment by dzhavat** [comment]
Hey @jdini76 
Thanks for reporting it! I just pushed a new version of the extension (v.1.2.0) with support for Cypress files. Can you give it a try? :)

**Comment by jdini76** [comment]
Thanks so much for the quick turn around on this.  So far things look good!

**Comment by dzhavat** [comment]
No problem :) 
Luckily it was an easy fix so I could implement it quickly. Thanks for using the extension.
